version: "3.8"
# All service running under similar composer
services:

# mongodb and client service
  db_mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeMe123
  mongo_express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db_mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: changeMe123
    depends_on:
      - db_mongo

# Your Application service
#  appOmsSvc:
#    image: gcr.io/beda-testing-dev/oms/base-service:185ef6a-2008111032
#    restart: always
#    ports:
#      - 8080:8080
#    expose:
#      - 8080
#    environment:
#      APP_VERSION: '0.0.1-RC'
#      APP_ENV: 'development'
#      DB_HOSTNAME: 'http://dbMsq'
#      DB_PORT: '3306'
#      DB_DATABASE: 'db-project-001'
#      DB_USERNAME: 'root'
#      DB_PASSWORD: 'changeMe123'
#      CACHE_HOSTNAME: 'http://redis'
#      CACHE_PORT: '6379'
#      CACHE_PASSWORD: 'changeMe123'
#      SC_USERNAME: 'changeMe123'
#      SC_PASSWORD: 'changeMe123'
#      SVC_CASHIER: 'http://sameple'
#    depends_on:
#      - db_mongo
#      - redis


